name: pfe_version1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_messaging: ^15.2.3
  flutter_local_notifications: ^19.1.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  intl: ^0.20.2
  permission_handler: ^12.0.0
  fl_chart: ^0.70.2
  rxdart: ^0.28.0
  share_plus: ^10.0.2
  path_provider: ^2.1.5
  excel: ^4.0.6
  csv: ^6.0.0
  universal_html: ^2.2.4
  google_sign_in: ^6.1.4
  google_fonts: ^6.2.1
  google_sign_in_web: ^0.12.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png