// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2tZnDw5v3i5EZg1CjAdXwQztGSYVWa50',
    appId: '1:576374987805:web:fa0bc8c9f364f00d8ffaf4',
    messagingSenderId: '576374987805',
    projectId: 'alertsys-80d0e',
    authDomain: 'alertsys-80d0e.firebaseapp.com',
    storageBucket: 'alertsys-80d0e.firebasestorage.app',
    measurementId: 'G-5RC789LLFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcZXhULRhMITDEXB4wt2_VFD9W8D1Vk2Y',
    appId: '1:576374987805:android:6ca2476b802272578ffaf4',
    messagingSenderId: '576374987805',
    projectId: 'alertsys-80d0e',
    storageBucket: 'alertsys-80d0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzrR7KckEcRfxOi_HQubCayMauccbIPL0',
    appId: '1:576374987805:ios:7deb609c3e12adf18ffaf4',
    messagingSenderId: '576374987805',
    projectId: 'alertsys-80d0e',
    storageBucket: 'alertsys-80d0e.firebasestorage.app',
    iosBundleId: 'com.example.pfeVersion1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2tZnDw5v3i5EZg1CjAdXwQztGSYVWa50',
    appId: '1:576374987805:web:44b922da7977bfcc8ffaf4',
    messagingSenderId: '576374987805',
    projectId: 'alertsys-80d0e',
    authDomain: 'alertsys-80d0e.firebaseapp.com',
    storageBucket: 'alertsys-80d0e.firebasestorage.app',
    measurementId: 'G-07FTG641QP',
  );
}
